artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1tSKSAmrmQ_kQz220GsMfaBMgTVga2IYB/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.rar
  unzip_dir: artifacts/data_ingestion